security:
    # Hashers de contraseña para usuarios que implementan PasswordAuthenticatedUserInterface
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # Proveedores de usuario
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    # Firewalls
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\AppCustomAuthenticator
            logout:
                path: app_logout
                # Redirección después de cerrar sesión
                target: app_login # Redirecciona al login tras logout

            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800  # Una semana en segundos
                path: /

            # Opciones adicionales de autenticación
            # switch_user: true

    # Control de acceso a rutas específicas
    access_control:
        # Aquí puedes añadir roles y restricciones de acceso a rutas específicas
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }

when@test:
    security:
        password_hashers:
            # Hashing más rápido para pruebas
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4        # Bcrypt
                time_cost: 3   # Argon2id
                memory_cost: 10 # Argon2id
